# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crypt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(259, 451)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(7)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(153, 15, 82);")
        self.btn_desencriptar = QtWidgets.QPushButton(Form)
        self.btn_desencriptar.setGeometry(QtCore.QRect(30, 320, 211, 51))
        self.btn_desencriptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_desencriptar.setStyleSheet("QPushButton{\n"
"    font-family: \'Acme\', sans-serif;\n"
"    font-size:9pt;\n"
"    background-color: #FFFFFF;\n"
"    background-repeat: space;\n"
"    border-radius:7px;\n"
"    \n"
"    background-image: url(:/icons/key.svg);\n"
"    }\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 0, 0);\n"
"    color:white\n"
"}")
        self.btn_desencriptar.setObjectName("btn_desencriptar")
        self.btn_encriptar = QtWidgets.QPushButton(Form)
        self.btn_encriptar.setGeometry(QtCore.QRect(30, 240, 211, 51))
        self.btn_encriptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_encriptar.setStyleSheet("QPushButton{\n"
"    font-family: \'Acme\', sans-serif;\n"
"    font-size:9pt;\n"
"    background-color: #FFFFFF;\n"
"    background-repeat: space;\n"
"    border-radius:7px;\n"
"    \n"
"    background-image: url(:/icons/lock.svg);\n"
"    }\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 0, 0);\n"
"    color:white;\n"
"    \n"
"    \n"
"}")
        self.btn_encriptar.setObjectName("btn_encriptar")
        self.btn_genera_clave = QtWidgets.QPushButton(Form)
        self.btn_genera_clave.setGeometry(QtCore.QRect(30, 90, 211, 51))
        self.btn_genera_clave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_genera_clave.setStyleSheet("QPushButton{\n"
"    font-family: \'Acme\', sans-serif;\n"
"    font-size:9pt;\n"
"    background-color: #FFFFFF;\n"
"    background-repeat: space;\n"
"    border-radius:7px;\n"
"background-image: url(:/icons/refresh-cw.svg);\n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 0, 0);\n"
"    color:white;\n"
"    \n"
"}\n"
"    ")
        self.btn_genera_clave.setObjectName("btn_genera_clave")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 20, 101, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.btn_buscar_archivo = QtWidgets.QPushButton(Form)
        self.btn_buscar_archivo.setGeometry(QtCore.QRect(30, 160, 211, 51))
        self.btn_buscar_archivo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_buscar_archivo.setStyleSheet("QPushButton{\n"
"    font-family: \'Acme\', sans-serif;\n"
"    font-size:9pt;\n"
"    background-color: #FFFFFF;\n"
"    background-repeat: space;\n"
"    border-radius:7px;\n"
"    }\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 0, 0);\n"
"    color:white\n"
"}\n"
"    ")
        self.btn_buscar_archivo.setObjectName("btn_buscar_archivo")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cripty App"))
        self.btn_desencriptar.setText(_translate("Form", "Desencriptar Archivo"))
        self.btn_encriptar.setText(_translate("Form", "Encriptar Archivo"))
        self.btn_genera_clave.setText(_translate("Form", "Generar Clave"))
        self.label.setText(_translate("Form", "Crypty App"))
        self.btn_buscar_archivo.setText(_translate("Form", "Buscar ..."))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
