# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crypt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(430, 540)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_encriptar = QtWidgets.QPushButton(Form)
        self.btn_encriptar.setGeometry(QtCore.QRect(40, 200, 341, 51))
        self.btn_encriptar.setStyleSheet("QPushButton{\n"
"    background-color: #FFFFFF;\n"
"    background-image: url(:/icons/lock.svg);\n"
"    font: 19px \"Nimbus Mono L\";\n"
"    background-repeat: space;\n"
"    border-radius:7px;\n"
"    }\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(249, 185, 196);\n"
"}")
        self.btn_encriptar.setObjectName("btn_encriptar")
        self.mensaje = QtWidgets.QLabel(Form)
        self.mensaje.setGeometry(QtCore.QRect(50, 370, 321, 101))
        self.mensaje.setMinimumSize(QtCore.QSize(321, 101))
        self.mensaje.setMaximumSize(QtCore.QSize(321, 101))
        self.mensaje.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mensaje.setText("")
        self.mensaje.setObjectName("mensaje")
        self.btn_genera_clave = QtWidgets.QPushButton(Form)
        self.btn_genera_clave.setGeometry(QtCore.QRect(40, 120, 341, 51))
        self.btn_genera_clave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_genera_clave.setStyleSheet("QPushButton{\n"
"    background-color: #FFFFFF;\n"
"    background-image: url(:/icons/refresh-cw.svg);\n"
"    font: 19px \"Nimbus Mono L\";\n"
"    background-repeat: space;\n"
"    border-radius:7px;\n"
"    }\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(249, 185, 196);\n"
"}\n"
"    ")
        self.btn_genera_clave.setObjectName("btn_genera_clave")
        self.btn_desencriptar = QtWidgets.QPushButton(Form)
        self.btn_desencriptar.setGeometry(QtCore.QRect(40, 280, 341, 51))
        self.btn_desencriptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_desencriptar.setStyleSheet("QPushButton{\n"
"    background-color: #FFFFFF;\n"
"    background-image: url(:/icons/unlock.svg);\n"
"    font: 19px \"Nimbus Mono L\";\n"
"    background-repeat: space;\n"
"    border-radius:7px;\n"
"    }\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(249, 185, 196);\n"
"}\n"
"    ")
        self.btn_desencriptar.setObjectName("btn_desencriptar")
        self.titulo = QtWidgets.QLabel(Form)
        self.titulo.setGeometry(QtCore.QRect(160, 30, 111, 41))
        self.titulo.setStyleSheet("font: 19px bold \"Nimbus Mono L\";\n"
"")
        self.titulo.setObjectName("titulo")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.btn_genera_clave, self.btn_encriptar)
        Form.setTabOrder(self.btn_encriptar, self.btn_desencriptar)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_encriptar.setText(_translate("Form", "Encriptar Archivo"))
        self.btn_genera_clave.setText(_translate("Form", "Generar Clave"))
        self.btn_desencriptar.setText(_translate("Form", "Desencriptar Archivo"))
        self.titulo.setText(_translate("Form", "Crypty Arch"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
