# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crypt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(430, 540)
        Form.setMinimumSize(QtCore.QSize(430, 540))
        Form.setMaximumSize(QtCore.QSize(430, 540))
        Form.setSizeIncrement(QtCore.QSize(430, 540))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_encriptar = QtWidgets.QPushButton(Form)
        self.btn_encriptar.setGeometry(QtCore.QRect(50, 320, 341, 51))
        self.btn_encriptar.setStyleSheet("QPushButton{\n"
"    background-color: #FFFFFF;\n"
"    background-image: url(:/icons/lock.svg);\n"
"    font: 19px \"Nimbus Mono L\";\n"
"    background-repeat: space;\n"
"    border-radius:7px;\n"
"    }\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(249, 185, 196);\n"
"}")
        self.btn_encriptar.setObjectName("btn_encriptar")
        self.btn_genera_clave = QtWidgets.QPushButton(Form)
        self.btn_genera_clave.setGeometry(QtCore.QRect(50, 80, 341, 51))
        self.btn_genera_clave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_genera_clave.setStyleSheet("QPushButton{\n"
"    background-color: #FFFFFF;\n"
"    background-image: url(:/icons/refresh-cw.svg);\n"
"    font: 19px \"Nimbus Mono L\";\n"
"    background-repeat: space;\n"
"    border-radius:7px;\n"
"    }\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(249, 185, 196);\n"
"}\n"
"    ")
        self.btn_genera_clave.setObjectName("btn_genera_clave")
        self.btn_desencriptar = QtWidgets.QPushButton(Form)
        self.btn_desencriptar.setGeometry(QtCore.QRect(50, 390, 341, 51))
        self.btn_desencriptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_desencriptar.setStyleSheet("QPushButton{\n"
"    background-color: #FFFFFF;\n"
"    background-image: url(:/icons/unlock.svg);\n"
"    font: 19px \"Nimbus Mono L\";\n"
"    background-repeat: space;\n"
"    border-radius:7px;\n"
"    }\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(249, 185, 196);\n"
"}\n"
"    ")
        self.btn_desencriptar.setObjectName("btn_desencriptar")
        self.titulo = QtWidgets.QLabel(Form)
        self.titulo.setGeometry(QtCore.QRect(160, 30, 111, 41))
        self.titulo.setStyleSheet("font: 19px bold \"Nimbus Mono L\";\n"
"color: #900C3F;\n"
"")
        self.titulo.setObjectName("titulo")
        self.btn_buscar = QtWidgets.QPushButton(Form)
        self.btn_buscar.setGeometry(QtCore.QRect(50, 240, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono L")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_buscar.setFont(font)
        self.btn_buscar.setStyleSheet("QPushButton{\n"
"    border-radius:7px; \n"
"    color:white;\n"
"    background-color: #900C3F;\n"
"    font: 20px \"Nimbus Mono L\";\n"
"}")
        self.btn_buscar.setObjectName("btn_buscar")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(50, 190, 341, 41))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: #FFFFFF;\n"
"    font: 17px \"Nimbus Mono L\";\n"
"    background-repeat: space;\n"
"    border-radius:7px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 160, 251, 20))
        self.label.setStyleSheet("font: 14px \"Nimbus Mono L\" bold;\n"
"color:#900C3F;")
        self.label.setObjectName("label")
        self.lineEdit.raise_()
        self.btn_genera_clave.raise_()
        self.btn_encriptar.raise_()
        self.btn_desencriptar.raise_()
        self.btn_buscar.raise_()
        self.titulo.raise_()
        self.label.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.btn_genera_clave, self.btn_encriptar)
        Form.setTabOrder(self.btn_encriptar, self.btn_desencriptar)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_encriptar.setText(_translate("Form", "Encriptar Archivo"))
        self.btn_genera_clave.setText(_translate("Form", "Generar Clave"))
        self.btn_desencriptar.setText(_translate("Form", "Desencriptar Archivo"))
        self.titulo.setText(_translate("Form", "Crypty Arch"))
        self.btn_buscar.setText(_translate("Form", "Buscar "))
        self.label.setText(_translate("Form", "Busque el Nombre del Archivo:"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
